"""Add organization, classification, status, description, remote_url to projects

Revision ID: 377f1471283c
Revises: 879b388fb5ae
Create Date: 2025-12-03 15:03:56.650925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377f1471283c'
down_revision = '879b388fb5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('classification', sa.Enum('primary', 'secondary', 'archive', 'maintenance', name='classification_enum'), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'paused', 'completed', 'cancelled', name='status_enum'), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('remote_url', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_organization'), ['organization'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_organization'))
        batch_op.drop_index(batch_op.f('ix_projects_classification'))
        batch_op.drop_column('remote_url')
        batch_op.drop_column('description')
        batch_op.drop_column('status')
        batch_op.drop_column('classification')
        batch_op.drop_column('organization')

    # ### end Alembic commands ###
