"""Add project_type enum column

Revision ID: e8b0673fe1a0
Revises: 377f1471283c
Create Date: 2025-12-23 16:29:11.675239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b0673fe1a0'
down_revision = '377f1471283c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.Enum('Work', 'Personal', 'Learning', 'Inactive', name='project_type_enum'), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_project_type'), ['project_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_type'))
        batch_op.drop_column('project_type')

    # ### end Alembic commands ###
